### ISSUE TITLE
Crash Kodi  when track is not "readable" 

### ISSUE THREAD

**Issue by Elwinmage** [Valentin271/DeezerKodi#1]
If a track is set to readable:"false" in deezer api, the script get a "Warning: mdecrypt_generic(): An empty string was passed in /data/vhosts/blm/smarttv/functions.php on line 188" and kodi crash.

Correction: in  play_track(id)
change last line with :
 _xbmcplugin.setResolvedUrl(addon_handle, False, **None**)_ 
to skip the track.

You can also research for the same song with a readble:"true" and replace it in your deezer playlist.

example: Shut Up and Dance (Walk the moon)

https://api.deezer.com/track/90326361 => readable:"false" => kodi crash or if previous patch is applied, the song is skipped

https://api.deezer.com/track/105757076 => readable:"yes", no problem

**Comment by Valentin271** [comment]
Thanks for pointing that out and giving a solution, it will be fixed in the next release.
I will also work on getting a readable track, hopefully in the next release too.

**Comment by Elwinmage** [comment]
Your very welcome :-)

Le 6 novembre 2019 22:02:43 GMT+01:00, Valentin271 <notifications@github.com> a écrit :
>Thanks for pointing that out and giving a solution, it will be fixed in
>the next release.
>I will also work on getting a readable track, hopefully in the next
>release too.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Valentin271/DeezerKodi/issues/1#issuecomment-550499028

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
