### ISSUE TITLE
Deezer Error

### ISSUE THREAD

**Issue by cerivera86** [Valentin271/DeezerKodi#10]
I installed the addon on Kodi 19 running on Nvidia Shield.
I put in my Deezer premiun account credentials in settings and once I open the addon it says "Deezer Error.... check the log for more details".
I don't have any previous versions installed just the latest one provided here.
I also tried it on my android phone and get the same error.
See attached screenshot.

Thanks
![Screenshot_20210411-075105_Kodi](https://user-images.githubusercontent.com/80178428/114309183-3aada900-9a9b-11eb-9c1a-5834536c059f.jpg)

**Comment by Valentin271** [comment]
Hello,

Are you sure your credentials are correct ?
Sometimes this happens for unknown reasons, try opening the addon again (up to 5 times).

If none of this works, please enable debug logging in Kodi by navigating to `Settings > System > Logging` and check `Enable debug logging`.
Then upload your log file here so I can debug what happened. See [this page](https://kodi.wiki/view/Log_file#Methods) for help on how to get your log file.
Once you uploaded the file, you can uncheck that option.

Thanks

**Comment by cerivera86** [comment]
Hello,

Thanks for the follow up.
I enter the credentials correctly. However when I signed up it gave me 3
months free trial of premium service. Technically my account is premium but
on trial. This might be the reason why throws an error?

**Comment by Valentin271** [comment]
That's a good question, I actually don't know.
In terms of database I think it is a premium account anyway so it's probably not the issue here.

I just checked again and loging is fine for me.
Could you give me your kodi log file so I can know what happens when you're trying to connect.

**Comment by cerivera86** [comment]
I reinstalled the repo and it worked.

Thanks for checking it out.

**Comment by Valentin271** [comment]
Happy to know it works now !
That's still a strange bug, maybe something went wrong while installing.
