### ISSUE TITLE
Listen to Deezer flow

### ISSUE THREAD

**Issue by noar12** [Valentin271/DeezerKodi#17]
It would be great to be able to listen to the automatically generated playlist called Deezer flow. Even better if we could chose between the ambiance ( party, focus, relax, etc)

**Comment by Valentin271** [comment]
Hello,

This feature is part of the 1.0.0 version that just released as of 16-11-2022.

It is pretty limited as I can only get 5 tracks or so from the API for flow.
Unfortunately, it is not possible to select the ambiance.

**Comment by noar12** [comment]
Hello,

Thanks a lot for this feature. It is working as you described. It even fetchs 8 songs instead of 5.
