### ISSUE TITLE
Kodi 18.6 issue

### ISSUE THREAD

**Issue by mflorezm** [Valentin271/DeezerKodi#2]
Hi Valentín, plug in 0.7 installs correctly but it shows error on kodon18.6 on librelec 9.2.1 for rpi4. It is a family account with three profiles and I am using the master login but it shows a register problem. See the attached log file image for the error.
![15988166512554144714509340549947](https://user-images.githubusercontent.com/7923418/91668095-4f6e9b00-eacf-11ea-9581-798a794904e4.jpg) thanks, Mfm

**Comment by mflorezm** [comment]
Hi again Valentin, the problem was that one of my profiles was written with ñ; changed and it began to work. As you said only family profiles work and personal is not working. Thanks.

**Comment by Valentin271** [comment]
Hello,
As you said, the ñ was the problem since it doesn't appear in the ascii table.
I'll quickly see if I can fix that.

For your information, I'am working on a new version that will include personal account.

Thanks for reporting this issue.

**Comment by Valentin271** [comment]
Hi again,

It should have been fixed, in [0.0.8](https://github.com/Valentin271/DeezerKodi/tree/v0.0.8).

If your problem is solved, mark the issue as closed.

**Comment by mflorezm** [comment]
Thanks
