### ISSUE TITLE
it doesn't work in nexus

### ISSUE THREAD

**Issue by batarela** [Valentin271/DeezerKodi#21]
Kodi v20 (Nexus) Pre-release Builds is out, Kodi v19 is under development but deezer addon only works in code 19.5. Valentin271 please make it work in Kodi v20 if possible.

**Comment by Valentin271** [comment]
Hello,

I've added compatibility for kodi 20 in version [2.0.3](https://github.com/Valentin271/DeezerKodi/releases/tag/v2.0.3).

If it still doesn't work, feel free to reopen this issue.
