### ISSUE TITLE
Plugin crashes immediately

### ISSUE THREAD

**Issue by freijon** [Valentin271/DeezerKodi#26]
Since a few days the plugin doesn't work at all. I can't even get go the screen where we select Personal / Search.

Here is my logfile: https://paste.kodi.tv/ipuzusosix

**Comment by Valentin271** [comment]
Hello,
Sorry for my late reply.

Does this still happen ?

**Comment by freijon** [comment]
Unfortunately yes

**Comment by Valentin271** [comment]
Could you provide me another log file ?

The previous one expired because I took so long to respond 😅

**Comment by freijon** [comment]
Sure, here you go: https://paste.kodi.tv/ecuhapuluq

**Comment by Valentin271** [comment]
At first glance, it looks like the file at `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/deezer-api.pickle` is empty, it shouldn't. If this is the case, deleting it should do the trick.

Let me know if that work, I can probably include some sort of failsafe.

**Comment by freijon** [comment]
That seems to have solved the issue, thank you! How can this happen all of a sudden?

**Comment by Valentin271** [comment]
Great!

My guess right now is a wrongly written file. The library I'm using for that doesn't say anything about this error. Maybe there is some differences in Android python execution too ...

Anyway I will probably include a failsafe deleting the file in case of this error.
