### ISSUE TITLE
browse saved Album or Artiste

### ISSUE THREAD

**Issue by vsaugey** [Valentin271/DeezerKodi#5]
**Describe the improvement**  
Should be great if the plugin permit to see album and artiste saved in the deezer account .

**Comment by Valentin271** [comment]
Hi,

Good idea, I'll work on that for the next major release.

Valentin

**Comment by anssiok** [comment]
Thanks for a great plug-in! It's solid work and works flawlessly. It just needs more features and this is the most important of them all. Thank you for good job so far!

**Comment by Valentin271** [comment]
Thank you for your support!

The feature has now been included in the release version 0.2.0. This version is compatible with both Kodi 18 and 19.
As usual your addon should be updated automatically, if not, download the newest version with the link in the README.

Hope you like this improvement.

**Comment by anssiok** [comment]
> Thank you for your support!
> 
> The feature has now been included in the release version 0.2.0. This version is compatible with both Kodi 18 and 19.
> As usual your addon should be updated automatically, if not, download the newest version with the link in the README.
> 
> Hope you like this improvement.

It works nicely, thank you very much!
