### ISSUE TITLE
No support for Kodi 19 Matrix and Python3

### ISSUE THREAD

**Issue by mattipunkt** [Valentin271/DeezerKodi#6]
This Addon makes an error when installing in Kodi 19, because its not set for Python3.

**Comment by Valentin271** [comment]
Hello,

Should be only small changes, I'll try to fix that as soon as possible.

Valentin

**Comment by Valentin271** [comment]
Hi,

Your issue has been resolved. You can try it out by installing the [alpha](https://github.com/Valentin271/DeezerKodi/raw/development/plugin.audio.deezer/plugin.audio.deezer-0.1.3-alpha1.zip) which fixes that.
If you don't have any other issue with it, let me know and I'll include it in the next release.

Valentin

**Comment by Valentin271** [comment]
Hello,

This issue is fixed in 123065635622e85360f7aec8a2e62fc06e1ca5fe, let me know if you have other issues.

Valentin
