### ISSUE TITLE
List more than 25 items

### ISSUE THREAD

**Issue by anssiok** [Valentin271/DeezerKodi#8]
The lists show the 25 first items and no more. For example, the discography of Metallica does not show any of their studio records because of all those live recording releases afterwards. Should there be a "show more" link or/and a user setting for the list length to show?

- OS: LibreELEC 9.2.6
- Kodi version: 18.9.0

**Comment by freijon** [comment]
I have the same issue and can't find any settings about this. It only lists the first 25 playlists and then stops. Is it a technical limitation?

**Comment by Valentin271** [comment]
Hello,

No technical limitation, just an error, I'll fix that as quick as possible.

Thank you for reporting that !

**Comment by Uukrull** [comment]
In fact, it's a limitation of the deezer api that only lists 25 albums at a time.
Replacing https://github.com/Valentin271/DeezerKodi/blob/8f3cc53f60c015394b8cbfc1d486322d14faf58f/src/resources/lib/DeezerApi/__init__.py#L798-L799 with 

```
        total = self.connection.make_request('artist', self.id, 'albums')['total']
        for i in range (total // 25 + 1):
            for a in self.connection.make_request('artist', self.id, 'albums', {'index': i*25})['data']:
                albums.append(Album(self.connection, a))

```

fixes the issue

**Comment by Uukrull** [comment]
The problem with your solution (an my older one) is that there are a lot of api requests capped to 25 results. For example, search for 'love' in tracks, albums and artists.

As an all-in-one solution, I found this to be working perfectly:

Change

https://github.com/Valentin271/DeezerKodi/blob/17d90247bf6954bfe85170f7eecd548a3b0cd1ca/src/resources/lib/DeezerApi/__init__.py#L171

to:

```
        response_json = json.loads(response.text)
        if 'next' in response_json:
            total = response_json['total']
            next = response_json['next']
            for i in range (1, total // 25 + 1):
                response = self.make_request_url(next)
                if 'next' in response:
                    next = response['next']
                response_json['data'].extend(response['data'])

        return response_json

```

**Comment by Valentin271** [comment]
Seems like the perfect solution since, as you said, every response is limited to 25 elements.
Recursive call in make_request_url might be easier to read and to implement but this is the right way to fix this issue for every listing.
I'll work on integrate that as soon as I can, hopefully this week.

**Comment by anssiok** [comment]
Why not to use "next page" link if the response exceeds 25 items?

**Comment by Valentin271** [comment]
I will use '_next_' link.
Basically, if I find a '_next_' key in the json response, I call `make_request_url `and save the return.
`make_request_url `should also do this check and call itself if it finds this key.


See this method for an exemple:

https://github.com/Valentin271/DeezerKodi/blob/17d90247bf6954bfe85170f7eecd548a3b0cd1ca/src/resources/lib/DeezerApi/__init__.py#L521

`get_tracks` query for the tracks if no `next_url` is given. It processes the response and then check for a '_next_' key in it.
If it finds one, it calls itself with the next url and add the call results to his.

**Comment by freijon** [comment]
I don't want to be pushy, but I'm eagerly waiting for this fix to be released. Do you have an ETA for when it will be released?

**Comment by Valentin271** [comment]
No problem you are right to remind me as the fix for this issue is implemented in the development branch.
I think I will make it available by the end of this week or shortly after.


**If you want it right now you can do the following :**

1. `git clone https://github.com/Valentin271/DeezerKodi.git DeezerKodi`
2. `cd DeezerKodi`
3. `git checkout development`
4. `python ./create_repository.py src`
5. Save the generated zip file `plugin.audio.deezer/plugin.audio.deezer-0.2.1.zip` to your Kodi box

**On your Kodi interface :**

6. Uninstall DeezerKodi
7. Reboot Kodi (or the device)
8. Install from the zip file copied in *step 5*

If you have trouble following theses insctructions I suggest to wait for the release.
